---
abstract: 'Terminal Interface Construction KIT'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::Builder::Tester: 0
  Test::Fatal: 0
  Test::HexString: 0
  Test::Identity: 0
  Test::More: 0
  Test::Refcount: 0
configure_requires:
  Alien::libtermkey: 0
  Alien::unibilium: 0
  ExtUtils::PkgConfig: 0
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit
provides:
  Tickit:
    file: lib/Tickit.pm
    version: 0.28
  Tickit::ContainerWidget:
    file: lib/Tickit/ContainerWidget.pm
    version: 0.28
  Tickit::OneLineWidget:
    file: lib/Tickit/OneLineWidget.pm
    version: 0.28
  Tickit::Pen:
    file: lib/Tickit/Pen.pm
    version: 0.28
  Tickit::Rect:
    file: lib/Tickit/Rect.pm
    version: 0.28
  Tickit::RectSet:
    file: lib/Tickit/RectSet.pm
    version: 0.28
  Tickit::SingleChildWidget:
    file: lib/Tickit/SingleChildWidget.pm
    version: 0.28
  Tickit::StringPos:
    file: lib/Tickit/StringPos.pm
    version: 0.28
  Tickit::Term:
    file: lib/Tickit/Term.pm
    version: 0.28
  Tickit::Test:
    file: lib/Tickit/Test.pm
    version: 0.28
  Tickit::Test::MockTerm:
    file: lib/Tickit/Test/MockTerm.pm
    version: 0.28
  Tickit::Utils:
    file: lib/Tickit/Utils.pm
    version: 0.28
  Tickit::Widget:
    file: lib/Tickit/Widget.pm
    version: 0.28
  Tickit::Widget::Box:
    file: lib/Tickit/Widget/Box.pm
    version: 0.28
  Tickit::Widget::HBox:
    file: lib/Tickit/Widget/HBox.pm
    version: 0.28
  Tickit::Widget::LinearBox:
    file: lib/Tickit/Widget/LinearBox.pm
    version: 0.28
  Tickit::Widget::Static:
    file: lib/Tickit/Widget/Static.pm
    version: 0.28
  Tickit::Widget::VBox:
    file: lib/Tickit/Widget/VBox.pm
    version: 0.28
  Tickit::WidgetRole:
    file: lib/Tickit/WidgetRole.pm
    version: 0.28
  Tickit::WidgetRole::Alignable:
    file: lib/Tickit/WidgetRole/Alignable.pm
    version: 0.28
  Tickit::WidgetRole::Borderable:
    file: lib/Tickit/WidgetRole/Borderable.pm
    version: 0.28
  Tickit::WidgetRole::Penable:
    file: lib/Tickit/WidgetRole/Penable.pm
    version: 0.28
  Tickit::Window:
    file: lib/Tickit/Window.pm
    version: 0.28
requires:
  Exporter: 5.57
  List::MoreUtils: 0
  perl: 5.010
resources:
  license: http://dev.perl.org/licenses/
version: 0.28
