---
abstract: 'Terminal Interface Construction KIT'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::Exception: 0
  Test::HexString: 0
  Test::Identity: 0
  Test::More: 0
  Test::Refcount: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit
provides:
  Tickit:
    file: lib/Tickit.pm
    version: 0.03
  Tickit::ContainerWidget:
    file: lib/Tickit/ContainerWidget.pm
    version: 0.03
  Tickit::Pen:
    file: lib/Tickit/Pen.pm
    version: 0.03
  Tickit::RootWindow:
    file: lib/Tickit/RootWindow.pm
    version: 0.03
  Tickit::Term:
    file: lib/Tickit/Term.pm
    version: 0.03
  Tickit::Widget:
    file: lib/Tickit/Widget.pm
    version: 0.03
  Tickit::Widget::Entry:
    file: lib/Tickit/Widget/Entry.pm
    version: 0.03
  Tickit::Widget::HBox:
    file: lib/Tickit/Widget/HBox.pm
    version: 0.03
  Tickit::Widget::LinearBox:
    file: lib/Tickit/Widget/LinearBox.pm
    version: 0.03
  Tickit::Widget::Static:
    file: lib/Tickit/Widget/Static.pm
    version: 0.03
  Tickit::Widget::VBox:
    file: lib/Tickit/Widget/VBox.pm
    version: 0.03
  Tickit::Window:
    file: lib/Tickit/Window.pm
    version: 0.03
requires:
  IO::Async: 0.29
  IO::Async::Stream: 0.34
  IO::Async::Test: 0
  List::MoreUtils: 0
  Term::Size: 0
  Term::TermKey::Async: 0
  Term::Terminfo: 0
  Text::CharWidth: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
